FIND_PATH(HELLO_INCLUDE_DIR hello.h /tmp/t2/usr/include/hello)
find_library(HELLO_LIBRARY NAMES hello PATHS /tmp/t2/usr/lib /home/zyh/cmakelearning/backup/cmake/t3/build/lib)

MESSAGE(${HELLO_INCLUDE_DIR})
MESSAGE(${HELLO_LIBRARY})


IF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    SET (HELLO_FOUND TRUE)
ENDIF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF(HELLO_FOUND)
    IF(NOT HELLO_FIND_QUIETLY)
        MESSAGE(STATUS "Found Hello: ${HELLO_LIBRARY}")
    ENDIF(HELLO_FIND_QUIETLY)
ELSE (HELLO_FOUND)
    IF (HELLO_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find hello library")
    ENDIF (HELLO_FIND_REQUIRED)
ENDIF (HELLO_FOUND)
